### ISSUE TITLE
Fix CV view on small screens

### ISSUE THREAD

**Issue by rymarm** [RaminKuraishy/git-course#2]
Fix CV view to make it look good on all screen sizes. 

❗️Achieve good view without using of JS.

How it looks on mobile devices now:
![Screenshot_20220320-123759_Chrome](https://user-images.githubusercontent.com/62295633/159174326-461f13b0-bcf3-4444-af68-8f361cda4ec1.jpg)

**Comment by RaminKuraishy** [comment]
add all adaptive for small screens and solve the problem
